#See also: https://github.com/bblanchon/ArduinoJson/blob/7.x/.github/workflows/ci.yml

name: PlatformIO CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
###     os: [ubuntu-latest, macos-latest, windows-latest]
###     example: [examples/00.HelloWorld/00.HelloWorld.ino, examples/02.QuadcopterAdvanced/02.QuadcopterAdvanced.ino]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up cache for pip
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build 00.HelloWorld
        run: pio ci --project-conf="extras/ci/ci_platformio.ini" --lib="." --lib="examples/00.HelloWorld" "examples/00.HelloWorld/00.HelloWorld.ino"
      - name: Build 02.QuadcopterAdvanced
        run: pio ci --project-conf="extras/ci/ci_platformio.ini" --lib="." --lib="examples/02.QuadcopterAdvanced" "examples/02.QuadcopterAdvanced/02.QuadcopterAdvanced.ino"

###   - name: Run PlatformIO
###     # NOTE: --lib="examples/00.HelloWorld" to get #include "madflight_config.h" to work...
###     run: pio ci --verbose --lib="." --lib="examples/00.HelloWorld" --project-conf="examples/platformio.ini"
###     env:
###       PLATFORMIO_CI_SRC: ${{ matrix.example }}

      - name: PlatformIO prune
        if: ${{ always() }}
        run: pio system prune -f
